### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#591]
Alrighty, we've got a few breaking changes that need to happen:

- [x] Respect defaultInputValue when provided #467
- [x] inputValue is set to empty string on select of already selected item #512
- [x] [Enhancement][Accessibility] When Listbox is closed, Up/Down should also highlight last/first option #589

And I have a few things I want to do:

- [x] upgrade all deps
- [x] move from storybook to [docz](https://docz.site) (will make cypress tests simpler and we may be able to actually use it for a legit site in the future... maybe now?) (related: https://github.com/paypal/downshift/issues/499)

As always, there are a handful of bugs that need investigating (I just went through and cleaned up the backlog).

I am confident that we can get this done today hopefully.

**Comment by kentcdodds** [comment]
Ok, so there are two things left:

- [ ] Fix react native tests
- [ ] Fix typescript tests

I'm unable to work on these. I may just push forward with a 3.0.0 as we are and we can fix those things later. Unless someone wants to grab those and look at what's going on?

**Comment by franklixuefei** [comment]
I can work on the typescript part, given that the documentation is updated so that I can just refer to it. :-)

**Comment by kentcdodds** [comment]
Yeah, not many changes, and the changes are documented. Thank you @franklixuefei!

**Comment by franklixuefei** [comment]
@kentcdodds Typescript tests errors are related to the outdated version of `@types/jquery` in `cypress`. 

cypress-io/cypress#2363
cypress-io/cypress#2369

Please take a look at my comment in the PR.

**Comment by kentcdodds** [comment]
Ok, so the reason the result failed is because we have the deps: docz -> docz-theme-default -> react-live -> buble -> acorn & acorn-jsx

And buble is using mismatched versions of acorn and acorn-jsx. That's been fixed in their repo, but it looks like it hasn't been published. So we can lock down buble to 0.19.3 until another version is released.
